language: node_js
node_js:
    - 6
sudo: false
before_install: npm i typescript koa@2 reflect-metadata @t2ee/core @t2ee/sl4js
install: npm install
script: npm test
after_script: npm run coverage && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
